=== slae2020/Bakki-the-stick/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
	
  <xs:element name="bk-script_options">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="general"/>
        <xs:element ref="directories"/>
        <xs:element ref="vergleiche"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="general">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="version"/>
        <xs:element name="verstxt" type="xs:string"/>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="text" type="xs:string"/>
        <xs:element name="config" type="xs:string"/>
        <xs:element name="confProg" type="xs:string"/>
        <xs:element name="meld" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="version">
    <xs:complexType mixed="true">
      <xs:attribute name="date" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="directories">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="homeVerz" type="xs:string"/>
        <xs:element name="stickort" type="xs:string"/>
        <xs:element name="StdVerz" type="xs:string"/>
        <xs:element name="RemoteOrt" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="vergleiche">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ordpaar" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="ordpaar">
    <xs:complexType>
      <xs:sequence>
		<xs:element name="id"   type="xs:string"/>  
        <xs:element name="name" type="xs:string"/>
        <xs:element name="dir1" type="xs:string"/>
        <xs:element name="dir2" type="xs:string"/>
      </xs:sequence>     
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== slae2020/Bakki-the-stick/kw.xml
<?xml version="1.0" encoding="UTF-8"?>

<bk-script_options xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/stefan/prog/bakki/Bakki-the-stick/config.xsd">

	<general>
		<version date="2024-07-01">1.1</version>	
		<verstxt> mit config.xml-Datei</verstxt>
		<title>Starter BK</title>
		<text>Meld-Vergleich auswählen (v$version;$verstxt)</text>
		<config>Einstellungen</config>
	</general>
	<directories>
		<homeVerz>/home/stefan</homeVerz>
		<stickort>/media/stefan</stickort>
		<StdVerz>/slaekim</StdVerz>
		<RemoteOrt>/mnt/iserv_laettig/Files</RemoteOrt>
	</directories>

	<vergleiche>

		<ordpaar id="00">
    <id>00</id>
		<name>SLAE01_#0</name>
		<dir1>~/slae_kim</dir1>
		<dir2>$stickort/SLAE01$StdVerz</dir2>
		</ordpaar>
		<ordpaar  id="01">
		<name>iservUSR_#1</name>
<!--
		<dir1>/home/stefan/slae_kim/usr</dir1>
-->
		<dir1>~/slae_kim/usr</dir1>
		<dir2>$RemoteOrt/usr</dir2>
		</ordpaar>
		<ordpaar>
		<name>iserv_unt#2</name>
		<dir1>~/slae_unt</dir1>
		<dir2>$RemoteOrt/unt</dir2>
		</ordpaar>
		<ordpaar id="MM">
		<name>iservAusdruck_#3</name>
		<dir1>~/slae_kim/ausdruck</dir1>
		<dir2>$RemoteOrt/ausdruck</dir2>
		</ordpaar>
		<ordpaar>
		<name id="04">ShuffleUnt_#4</name>
		<dir1>~/slae_kim/abf</dir1>
		<dir2>~/slae_unt</dir2>
		</ordpaar>
		
		<ordpaar>
		<name>SLAE03_#5</name>
		<dir1>~/slae_kim</dir1>
		<dir2>$stickort/SLAE03$StdVerz</dir2>
		</ordpaar>	
		
		<ordpaar>
		<name>Keepass_#6</name>
		<dir1>~/.door3</dir1>
		<dir2>$RemoteOrt/kp/myt</dir2>
		</ordpaar>
		<ordpaar>
		<name>meld_#10</name>
		<dir1></dir1>
		<dir2></dir2>
		</ordpaar>
	</vergleiche>

</bk-script_options>
<!-- Ende des XML-Dokumentes -->
<!-- keine Lücken im Namen ; keine ~/ in Verzeichnissen -->
<!--
>>>>>>> cf06b07 (Mo Pause 2)
		<ordpaar>
		<name>test</name>
		<dir1>~/prog/as</dir1>
		<dir2>/home/woher/</dir2>
		</ordpaar>
		<ordpaar>
		<name>test2</name>
		<dir1>~/slae_kim/usr</dir1>
		<dir2>/home/woher/</dir2>
		</ordpaar>
</bk-script_options>
-->
<!-- Ende des XML-Dokumentes -->
